type CacheEnvelope<T> = {
  data: T;
  cachedAt: number;
};

const memoryCache = new Map<string, CacheEnvelope<unknown>>();

const MAX_LOCALSTORAGE_BYTES = 200 * 1024;

const getCurrentUserId = (): string => {
  try {
    const raw = localStorage.getItem('presently_user');

    if (!raw) {
      return 'anonymous';
    }

    const user = JSON.parse(raw) as {
      userId?: string;
      id?: string;
    };

    return String(user.userId || user.id || 'anonymous');
  } catch {
    return 'anonymous';
  }
};

const safeParse = <T>(
  raw: string | null
): CacheEnvelope<T> | null => {
  if (!raw) return null;

  try {
    const parsed = JSON.parse(raw);

    // New cache format:
    // { data: ..., cachedAt: ... }
    if (
      parsed &&
      typeof parsed === 'object' &&
      'data' in parsed &&
      'cachedAt' in parsed
    ) {
      return parsed as CacheEnvelope<T>;
    }

    // Backwards compatibility with the old Presently
    // cache format where the value itself was stored.
    return {
      data: parsed as T,
      cachedAt: 0
    };
  } catch {
    return null;
  }
};

export const CacheService = {
  /**
   * Returns the currently authenticated user's ID.
   *
   * This is used by ApiService to create user-scoped
   * cache keys.
   */
  userId(): string {
    return getCurrentUserId();
  },

  /**
   * Read a cache entry including its timestamp.
   */
  get<T>(key: string): CacheEnvelope<T> | null {
    // 1. Memory cache first.
    const memory = memoryCache.get(key);

    if (memory) {
      return memory as CacheEnvelope<T>;
    }

    // 2. localStorage fallback.
    try {
      const entry = safeParse<T>(
        localStorage.getItem(key)
      );

      if (!entry) {
        return null;
      }

      // Populate memory cache so subsequent reads
      // are faster than localStorage.
      memoryCache.set(
        key,
        entry as CacheEnvelope<unknown>
      );

      return entry;
    } catch {
      return null;
    }
  },

  /**
   * Read only the cached data.
   */
  getData<T>(key: string): T | null {
    return CacheService.get<T>(key)?.data ?? null;
  },

  /**
   * Store data in both memory and localStorage.
   */
  set<T>(
    key: string,
    data: T
  ): void {
    const entry: CacheEnvelope<T> = {
      data,
      cachedAt: Date.now()
    };

    memoryCache.set(
      key,
      entry as CacheEnvelope<unknown>
    );

    try {
      const serialized = JSON.stringify(entry);
      if (serialized.length > MAX_LOCALSTORAGE_BYTES) {
        return;
      }
      localStorage.setItem(
        key,
        serialized
      );
    } catch {
    }
  },

  /**
   * Return cache age in milliseconds.
   */
  age(key: string): number | null {
    const entry = this.get(key);

    if (!entry) {
      return null;
    }

    return Math.max(
      0,
      Date.now() - entry.cachedAt
    );
  },

  /**
   * Remove one cache entry.
   */
  invalidate(key: string): void {
    memoryCache.delete(key);

    try {
      localStorage.removeItem(key);
    } catch {
      // Ignore storage errors.
    }
  },

  /**
   * Remove all cache entries beginning with a prefix.
   */
  invalidatePrefix(prefix: string): void {
    // Remove from memory.
    Array.from(memoryCache.keys()).forEach(
      key => {
        if (key.startsWith(prefix)) {
          memoryCache.delete(key);
        }
      }
    );

    // Remove from localStorage.
    try {
      Object.keys(localStorage).forEach(
        key => {
          if (key.startsWith(prefix)) {
            localStorage.removeItem(key);
          }
        }
      );
    } catch {
      // Ignore storage errors.
    }
  },

  /**
   * Clear ONLY the specified user's Presently cache.
   *
   * IMPORTANT:
   * Do not use `presently:` alone here because that
   * would clear caches belonging to other users.
   */
  clearUserCache(userId: string): void {
    const prefix = `presently:`;

    // Cache keys generated by ApiService have the
    // user ID somewhere after the resource name, so
    // remove only keys containing this exact user ID.
    const userMarker = `:${userId}`;

    Array.from(memoryCache.keys()).forEach(
      key => {
        if (
          key.startsWith(prefix) &&
          key.includes(userMarker)
        ) {
          memoryCache.delete(key);
        }
      }
    );

    try {
      Object.keys(localStorage).forEach(
        key => {
          if (
            key.startsWith(prefix) &&
            key.includes(userMarker)
          ) {
            localStorage.removeItem(key);
          }
        }
      );
    } catch {
      // Ignore storage errors.
    }
  }
};